# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FDSreader testsuite

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'fdsreader/'
  pull_request:
    paths:
      - 'fdsreader/'

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Prepare test cases
      run: |
        cd tests/cases/
        for f in *.tar.gz; do tar -xvf "$f"; done
    - name: Test with pytest
      run: |
        pytest tests/acceptance_tests
